version: "3.8"

services:
  image_db_backend_test:
    build: .
    container_name: IDB_backend_test
    ports:
      - "5002:5002"
      - "5001:5001"
    volumes:
      - /Users/artempriadkin/Documents/IDBVolume/filesVolume:/app/dataBase
      - /Users/artempriadkin/Documents/IDBVolume/previews:/app/previews
    restart: unless-stopped

  mongo-test:
    image : mongo:4.4
    container_name: IDB_mongodb_test
    user: nobody
    volumes:
      - /Users/artempriadkin/Documents/IDBVolume/mongodb:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
