version: "3.8"

services:
  image_db_backend_dev:
    build: .
    container_name: IDB_backend_dev
    ports:
      - "5002:5002"
      - "5001:5001"
    volumes:
      - .:/app
      - /app/node_modules
      - ../dev-volumes/database:/app/dataBase
      - ../dev-volumes/previews:/app/previews
    restart: unless-stopped

  mongo-dev:
    image : mongo:4.4
    container_name: IDB_mongodb_dev
    user: nobody
    volumes:
      - ../dev-volumes/mongoDB:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
