version: "3.8"

services:
  image_db_backend_test_volume:
    build: .
    container_name: IDB_backend_test_volume
    ports:
      - "5002:5002"
      - "5001:5001"
    volumes:
      - .:/app
      - /app/node_modules
      - /Volumes/Seagate 2TB/IDBVolume/filesVolume:/app/dataBase
      - /Volumes/Seagate 2TB/IDBVolume/previews:/app/previews
    restart: unless-stopped

  mongo-test:
    image : mongo:4.4
    container_name: IDB_mongodb
    user: nobody
    volumes:
      - /Volumes/Seagate 2TB/IDBVolume/mongodb:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
