version: "3.8"

services:
  image_db_backend:
    build: .
    container_name: IDB_backend
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
    #  - /Volumes/Transcend V/Yandex.Disk.localized/IDBase/filesVolume:/app/dataBase
      - /Volumes/Seagate 2TB/Yandex.Disk.localized/IDBase/filesVolume:/app/dataBase
      - /Volumes/Seagate 2TB/Yandex.Disk.localized/IDBase/previews:/app/previews
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    container_name: IDB_mongodb
    user: nobody
    volumes:
      - /Volumes/Seagate 2TB/Yandex.Disk.localized/IDBase/mongodb:/data/db
    #  - /Volumes/Transcend V/Yandex.Disk.localized/IDBase/mongodb:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
